/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author MARTHA
 */
public class VentanaDivisas extends javax.swing.JFrame {

    private String divisa1 = "";
    private String divisa2 = "";
    private String cantidad = "";
    private double dinero, cambio;
    private boolean punto = true;

    /**
     * Creates new form VentanaDivisas
     */
    public VentanaDivisas() {
        initComponents();
        setSize(300, 450);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jButton1 = new javax.swing.JButton();
        Panel = new javax.swing.JPanel();
        EtiquetaDivisa = new javax.swing.JLabel();
        EtiquetaCambio1 = new javax.swing.JLabel();
        ComboDivisas1 = new javax.swing.JComboBox<>();
        EtiquetaDivisa2 = new javax.swing.JLabel();
        EtiquetaCambio2 = new javax.swing.JLabel();
        ComboDivisas2 = new javax.swing.JComboBox<>();
        BotonC = new javax.swing.JButton();
        BotonBorrar = new javax.swing.JButton();
        Boton1 = new javax.swing.JButton();
        Boton2 = new javax.swing.JButton();
        Boton3 = new javax.swing.JButton();
        Boton4 = new javax.swing.JButton();
        Boton5 = new javax.swing.JButton();
        Boton6 = new javax.swing.JButton();
        Boton7 = new javax.swing.JButton();
        Boton8 = new javax.swing.JButton();
        Boton9 = new javax.swing.JButton();
        Boton0 = new javax.swing.JButton();
        BotonPunto = new javax.swing.JButton();
        BarraMenu = new javax.swing.JMenuBar();
        Menu = new javax.swing.JMenu();
        MenuCalculadora = new javax.swing.JMenuItem();
        MenuDivisas = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        MenuSalir = new javax.swing.JMenuItem();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Panel.setLayout(new java.awt.GridBagLayout());

        EtiquetaDivisa.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        EtiquetaDivisa.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        EtiquetaDivisa.setText("$");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(15, 15, 0, 10);
        Panel.add(EtiquetaDivisa, gridBagConstraints);

        EtiquetaCambio1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        EtiquetaCambio1.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(15, 0, 0, 0);
        Panel.add(EtiquetaCambio1, gridBagConstraints);

        ComboDivisas1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        ComboDivisas1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Estados Unidos- Dolar", "Perú- Sol", "Europa-Euro" }));
        ComboDivisas1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboDivisas1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        Panel.add(ComboDivisas1, gridBagConstraints);

        EtiquetaDivisa2.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        EtiquetaDivisa2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        EtiquetaDivisa2.setText("$");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(15, 15, 0, 10);
        Panel.add(EtiquetaDivisa2, gridBagConstraints);

        EtiquetaCambio2.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        EtiquetaCambio2.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(15, 0, 0, 0);
        Panel.add(EtiquetaCambio2, gridBagConstraints);

        ComboDivisas2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        ComboDivisas2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Estados Unidos- Dolar", "Perú- Sol", "Europa-Euro" }));
        ComboDivisas2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboDivisas2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        Panel.add(ComboDivisas2, gridBagConstraints);

        BotonC.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        BotonC.setText("C");
        BotonC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(15, 0, 0, 0);
        Panel.add(BotonC, gridBagConstraints);

        BotonBorrar.setIcon(new javax.swing.ImageIcon("C:\\Users\\MARTHA\\Desktop\\iconos Calculadora\\borrar.png")); // NOI18N
        BotonBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonBorrarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(15, 0, 0, 0);
        Panel.add(BotonBorrar, gridBagConstraints);

        Boton1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Boton1.setText("1");
        Boton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        Panel.add(Boton1, gridBagConstraints);

        Boton2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Boton2.setText("2");
        Boton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        Panel.add(Boton2, gridBagConstraints);

        Boton3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Boton3.setText("3");
        Boton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton3ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        Panel.add(Boton3, gridBagConstraints);

        Boton4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Boton4.setText("4");
        Boton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton4ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        Panel.add(Boton4, gridBagConstraints);

        Boton5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Boton5.setText("5");
        Boton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton5ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        Panel.add(Boton5, gridBagConstraints);

        Boton6.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Boton6.setText("6");
        Boton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton6ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        Panel.add(Boton6, gridBagConstraints);

        Boton7.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Boton7.setText("7");
        Boton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton7ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        Panel.add(Boton7, gridBagConstraints);

        Boton8.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Boton8.setText("8");
        Boton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton8ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        Panel.add(Boton8, gridBagConstraints);

        Boton9.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Boton9.setText("9");
        Boton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton9ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        Panel.add(Boton9, gridBagConstraints);

        Boton0.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Boton0.setText("0");
        Boton0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton0ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        Panel.add(Boton0, gridBagConstraints);

        BotonPunto.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        BotonPunto.setText(".");
        BotonPunto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonPuntoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        Panel.add(BotonPunto, gridBagConstraints);

        Menu.setText("Usos");
        Menu.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        MenuCalculadora.setIcon(new javax.swing.ImageIcon("C:\\Users\\MARTHA\\Desktop\\iconos Calculadora\\calculadora.png")); // NOI18N
        MenuCalculadora.setText("Calculadora Estandar");
        MenuCalculadora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuCalculadoraActionPerformed(evt);
            }
        });
        Menu.add(MenuCalculadora);

        MenuDivisas.setIcon(new javax.swing.ImageIcon("C:\\Users\\MARTHA\\Desktop\\iconos Calculadora\\divisas.png")); // NOI18N
        MenuDivisas.setText("Conversor Divisas");
        Menu.add(MenuDivisas);
        Menu.add(jSeparator1);

        MenuSalir.setIcon(new javax.swing.ImageIcon("C:\\Users\\MARTHA\\Desktop\\iconos Calculadora\\Salir.png")); // NOI18N
        MenuSalir.setText("Salir");
        MenuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuSalirActionPerformed(evt);
            }
        });
        Menu.add(MenuSalir);

        BarraMenu.add(Menu);

        setJMenuBar(BarraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel, javax.swing.GroupLayout.DEFAULT_SIZE, 428, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuSalirActionPerformed
        // TODO add your handling code here:

        System.exit(0);
    }//GEN-LAST:event_MenuSalirActionPerformed

    private void MenuCalculadoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuCalculadoraActionPerformed
        // TODO add your handling code here:

        Ventana_Calculadora calculadora = new Ventana_Calculadora();

        calculadora.setVisible(true);

        dispose();
    }//GEN-LAST:event_MenuCalculadoraActionPerformed

    private void ComboDivisas1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboDivisas1ActionPerformed
        // TODO add your handling code here:

        divisa1 = (String) ComboDivisas1.getSelectedItem();

        if (divisa1.equals("Estados Unidos- Dolar")) {

            EtiquetaDivisa.setText("$");
        } else if (divisa1.equals("Perú- Sol")) {
            EtiquetaDivisa.setText("S/.");
        } else if (divisa1.equals("Europa-Euro")) {
            EtiquetaDivisa.setText("€");
        }
        ObtenerDinero();
    }//GEN-LAST:event_ComboDivisas1ActionPerformed

    private void ComboDivisas2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboDivisas2ActionPerformed
        // TODO add your handling code here:
        divisa2 = (String) ComboDivisas2.getSelectedItem();

        if (divisa2.equals("Estados Unidos- Dolar")) {
            EtiquetaDivisa2.setText("$");
        } else if (divisa2.equals("Perú- Sol")) {
            EtiquetaDivisa2.setText("S/.");
        } else if (divisa2.equals("Europa-Euro")) {
            EtiquetaDivisa2.setText("€");
        }
        ObtenerDinero();
    }//GEN-LAST:event_ComboDivisas2ActionPerformed

    private void Boton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton1ActionPerformed
        // TODO add your handling code here:
        if (EtiquetaCambio1.getText() == "0") {
            cantidad = "1";
        } else {
            cantidad += "1";
        }
        EtiquetaCambio1.setText(cantidad);
        ObtenerDinero();
    }//GEN-LAST:event_Boton1ActionPerformed

    private void Boton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton2ActionPerformed
        // TODO add your handling code here:
        if (EtiquetaCambio1.getText() == "0") {
            cantidad = "2";
        } else {
            cantidad += "2";
        }
        EtiquetaCambio1.setText(cantidad);
        ObtenerDinero();
    }//GEN-LAST:event_Boton2ActionPerformed

    private void Boton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton3ActionPerformed
        if (EtiquetaCambio1.getText() == "0") {
            cantidad = "3";
        } else {
            cantidad += "3";
        }

        EtiquetaCambio1.setText(cantidad);
        ObtenerDinero();
    }//GEN-LAST:event_Boton3ActionPerformed

    private void Boton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton4ActionPerformed
        // TODO add your handling code here:

        if (EtiquetaCambio1.getText() == "0") {
            cantidad = "4";
        } else {
            cantidad += "4";
        }

        EtiquetaCambio1.setText(cantidad);
        ObtenerDinero();
    }//GEN-LAST:event_Boton4ActionPerformed

    private void Boton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton5ActionPerformed
        // TODO add your handling code here:

        if (EtiquetaCambio1.getText() == "0") {
            cantidad = "5";
        } else {
            cantidad += "5";
        }

        EtiquetaCambio1.setText(cantidad);
        ObtenerDinero();
    }//GEN-LAST:event_Boton5ActionPerformed

    private void Boton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton6ActionPerformed
        // TODO add your handling code here:

        if (EtiquetaCambio1.getText() == "0") {
            cantidad = "6";
        } else {
            cantidad += "6";
        }

        EtiquetaCambio1.setText(cantidad);
        ObtenerDinero();
    }//GEN-LAST:event_Boton6ActionPerformed

    private void Boton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton7ActionPerformed
        // TODO add your handling code here:
        if (EtiquetaCambio1.getText() == "0") {
            cantidad = "7";
        } else {
            cantidad += "7";
        }

        EtiquetaCambio1.setText(cantidad);
        ObtenerDinero();
    }//GEN-LAST:event_Boton7ActionPerformed

    private void Boton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton8ActionPerformed
        // TODO add your handling code here:
        if (EtiquetaCambio1.getText() == "0") {
            cantidad = "8";
        } else {
            cantidad += "8";
        }

        EtiquetaCambio1.setText(cantidad);
        ObtenerDinero();
    }//GEN-LAST:event_Boton8ActionPerformed

    private void Boton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton9ActionPerformed
        // TODO add your handling code here:
        if (EtiquetaCambio1.getText() == "0") {
            cantidad = "9";
        } else {
            cantidad += "9";
        }

        EtiquetaCambio1.setText(cantidad);
        ObtenerDinero();
    }//GEN-LAST:event_Boton9ActionPerformed

    private void Boton0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton0ActionPerformed
        // TODO add your handling code here:
        if (cantidad != "") {
            if (EtiquetaCambio1.getText() == "0") {
                cantidad = "0";
            } else {
                cantidad += "0";
            }
            EtiquetaCambio1.setText(cantidad);
            ObtenerDinero();
        }
    }//GEN-LAST:event_Boton0ActionPerformed

    private void BotonPuntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonPuntoActionPerformed
        if (punto == true) {
            if (cantidad == "") {
                cantidad = "0.";
            } else {
                cantidad += ".";
            }
            EtiquetaCambio1.setText(cantidad);
            punto=false;
        }


    }//GEN-LAST:event_BotonPuntoActionPerformed

    private void BotonCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCActionPerformed
        // TODO add your handling code here:
        cantidad="";
        punto=true;
        EtiquetaCambio1.setText("0");
        EtiquetaCambio2.setText("0");
    }//GEN-LAST:event_BotonCActionPerformed

    private void BotonBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonBorrarActionPerformed
        // TODO add your handling code here:
        int tamaño= cantidad.length();
        if(tamaño>0){
            if(tamaño==1){
                cantidad="0";
            }else{
                cantidad=cantidad.substring(0,cantidad.length()-1);
            }
            EtiquetaCambio1.setText(cantidad);
            ObtenerDinero();
        }
        
    }//GEN-LAST:event_BotonBorrarActionPerformed
    private void ObtenerDinero() {
        cantidad = EtiquetaCambio1.getText();
        dinero = Double.parseDouble(cantidad);
        CambioDivisas();
        dinero *= cambio;
        EtiquetaCambio2.setText(String.format("%.2f", dinero));
    }

    private void CambioDivisas() {

        if (divisa1.equals(divisa2)) {
            cambio = 1;
        } else if (divisa1.equals("Estados Unidos- Dolar") && divisa2.equals("Perú- Sol")) {
            cambio = 3.25;
        } else if (divisa1.equals("Estados Unidos- Dolar") && divisa2.equals("Europa-Euro")) {
            cambio = 0.84;
        } else if (divisa1.equals("Perú- Sol") && divisa2.equals("Estados Unidos- Dolar")) {
            cambio = 0.32;
        } else if (divisa1.equals("Perú- Sol") && divisa2.equals("Europa-Euro")) {
            cambio = 0.26;
        } else if (divisa1.equals("Europa-Euro") && divisa2.equals("Estados Unidos- Dolar")) {
            cambio = 1.2;
        } else if (divisa1.equals("Europa-Euro") && divisa2.equals("Perú- Sol")) {
            cambio = 3.91;
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaDivisas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaDivisas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaDivisas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaDivisas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaDivisas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar BarraMenu;
    private javax.swing.JButton Boton0;
    private javax.swing.JButton Boton1;
    private javax.swing.JButton Boton2;
    private javax.swing.JButton Boton3;
    private javax.swing.JButton Boton4;
    private javax.swing.JButton Boton5;
    private javax.swing.JButton Boton6;
    private javax.swing.JButton Boton7;
    private javax.swing.JButton Boton8;
    private javax.swing.JButton Boton9;
    private javax.swing.JButton BotonBorrar;
    private javax.swing.JButton BotonC;
    private javax.swing.JButton BotonPunto;
    private javax.swing.JComboBox<String> ComboDivisas1;
    private javax.swing.JComboBox<String> ComboDivisas2;
    private javax.swing.JLabel EtiquetaCambio1;
    private javax.swing.JLabel EtiquetaCambio2;
    private javax.swing.JLabel EtiquetaDivisa;
    private javax.swing.JLabel EtiquetaDivisa2;
    private javax.swing.JMenu Menu;
    private javax.swing.JMenuItem MenuCalculadora;
    private javax.swing.JMenuItem MenuDivisas;
    private javax.swing.JMenuItem MenuSalir;
    private javax.swing.JPanel Panel;
    private javax.swing.JButton jButton1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
